name: final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  google_mlkit_face_detection: ^0.13.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
